@startuml
!theme plain

skinparam rectangle {
    BackgroundColor LightYellow
    BorderColor Red
}

skinparam node {
    BackgroundColor LightBlue
    BorderColor Black
}


rectangle "raft" {
    node "Node1 [Leader]" as N1 {
        artifact "Log=[\n  x=1, \n]" as N1_1
        artifact "Term=1" as N1_2
        artifact "CommitIndex=1" as N1_3
        artifact "ApplyIndex=1" as N1_4
        artifact "State={\n   x: 1, \n}" as N1_5
    }
    N1_1 -D- N1_2
    N1_2 -D- N1_3
    N1_3 -D- N1_4
    N1_4 -D- N1_5

    node "Node2 [Follower]" as N2 {
        artifact "Log=[]" as N2_1
        artifact "Term=0" as N2_2
        artifact "CommitIndex=0" as N2_3
        artifact "ApplyIndex=0" as N2_4
        artifact "State={}" as N2_5
    }
    N2_1 -D- N2_2
    N2_2 -D- N2_3
    N2_3 -D- N2_4
    N2_4 -D- N2_5

    node "Node3 [Follower]" as N3 {
        artifact "Log=[]" as N3_1
        artifact "Term=0" as N3_2
        artifact "CommitIndex=0" as N3_3
        artifact "ApplyIndex=0" as N3_4
        artifact "State={}" as N3_5
    }
    N3_1 -D- N3_2
    N3_2 -D- N3_3
    N3_3 -D- N3_4
    N3_4 -D- N3_5
}

N1 <-D- N2 : join
N1 <-D- N3 : join

@enduml
